# Generated by Django 6.0 on 2026-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_choice', models.CharField(max_length=100, verbose_name='Enter name of the product')),
                ('status_bs', models.CharField(choices=[('BUY', 'BUY'), ('NOT_BUY', 'NOT_BUY')], default='NOT_BUY', max_length=100, verbose_name='enter your status')),
            ],
            options={
                'verbose_name': 'basket',
                'verbose_name_plural': 'baskets',
            },
        ),
    ]
