# Generated by Django 6.0 on 2025-12-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('describition', models.TextField()),
                ('type_priducts', models.CharField(choices=[('Education', 'Education'), ('Travel', 'Travel')], default='Education', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
