# Generated by Django 6.0 on 2026-01-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_review_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='type_priducts',
        ),
        migrations.AddField(
            model_name='products',
            name='type_products',
            field=models.CharField(choices=[('Education', 'Education'), ('Travel', 'Travel')], default='Education', max_length=100),
        ),
    ]
